<?php

namespace AppBundle\Repository;

/**
 * ABCWorksheetAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ABCWorksheetAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
