<?php

namespace AppBundle\Repository;

/**
 * ABMAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ABMAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
