<?php

namespace AppBundle\Repository;

/**
 * ABMIcebreakerQuestionSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ABMIcebreakerQuestionSetRepository extends \Doctrine\ORM\EntityRepository
{
}
