<?php

namespace AppBundle\Repository;

/**
 * AdjectiveAmpedChoiceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdjectiveAmpedChoiceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
