<?php

namespace AppBundle\Repository;

/**
 * AmpedChoiceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmpedChoiceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
