<?php

namespace AppBundle\Repository;

/**
 * ampedsessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ampedsessionRepository extends \Doctrine\ORM\EntityRepository
{
}
