<?php

namespace AppBundle\Repository;

/**
 * AmpedTextareaTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmpedTextareaTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
