<?php

namespace AppBundle\Repository;

/**
 * AnswerSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerSetRepository extends \Doctrine\ORM\EntityRepository
{
    public function getIcebreakerAnswers($session)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb
                ->select('a')
                ->from('AppBundle\Entity\AnswerSet', 'a')
                ->join('a.session', 's')
                ->where($qb->expr()->eq('s', '?1'))
                ->andWhere('(a INSTANCE OF AppBundle\Entity\ABMAnswers) OR (a INSTANCE OF AppBundle\Entity\ThingsInCommonAnswers) OR (a INSTANCE OF AppBundle\Entity\MeShieldAnswers) OR (a INSTANCE OF AppBundle\Entity\SevenWordsAnswers) OR (a INSTANCE OF AppBundle\Entity\TimeTravelingAnswers) OR (a INSTANCE OF AppBundle\Entity\BackpackScavengerAnswers)')
                        //. 'OR a INSTANCE OF AppBundle\Entity\MeShieldAnswers OR a INSTANCE OF AppBundle\Entity\SevenWordsAnswers'
                        //. 'a INSTANCE OF AppBundle\Entity\TimeTravelingAnswers OR a INSTANCE OF AppBundle\Entity\BackpackScavengerAnswers')
                ->setParameter(1, $session)
                ->getQuery()
                ->setMaxResults(1)
        ->getOneOrNullResult();
    }
    public function getModuleAnswers($session)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb
                ->select('a')
                ->from('AppBundle\Entity\AnswerSet', 'a')
                ->join('a.session', 's')
                ->where($qb->expr()->eq('s', '?1'))
                ->setParameter(1, $session)
                ->andWhere('(a INSTANCE OF AppBundle\Entity\BehaviourLogAnswers) OR (a INSTANCE OF AppBundle\Entity\GPAWorksheetAnswers) '
                        . 'OR (a INSTANCE OF AppBundle\Entity\ConflictResAnswers) OR (a INSTANCE OF AppBundle\Entity\BrainstormingWorksheetAnswers) '
                        . 'OR (a INSTANCE OF AppBundle\Entity\MotivationWorksheetAnswers) OR (a INSTANCE OF AppBundle\Entity\ABCWorksheetAnswers)')
                ->getQuery()
                ->setMaxResults(1)
        ->getOneOrNullResult();
    }
    
}
