<?php

namespace AppBundle\Repository;

/**
 * BackpackScavengerAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackpackScavengerAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
