<?php

namespace AppBundle\Repository;

/**
 * BehaviourLogAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BehaviourLogAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
