<?php

namespace AppBundle\Repository;

/**
 * BrainstormingWorksheetAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrainstormingWorksheetAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
