<?php

namespace AppBundle\Repository;

/**
 * ChangeFormMiscQuestionSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangeFormMiscQuestionSetRepository extends \Doctrine\ORM\EntityRepository
{
}
