<?php

namespace AppBundle\Repository;

/**
 * ChangeSurveyAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangeSurveyAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
