<?php

namespace AppBundle\Repository;

/**
 * ConflictResAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConflictResAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
