<?php

namespace AppBundle\Repository;

/**
 * DefinitiveAmpedChoiceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefinitiveAmpedChoiceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
