<?php

namespace AppBundle\Repository;

/**
 * GoalSheetAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoalSheetAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
