<?php

namespace AppBundle\Repository;

/**
 * GPAWorksheetAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GPAWorksheetAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
