<?php

namespace AppBundle\Repository;

/**
 * IcebreakerQuestionSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IcebreakerQuestionSetRepository extends \Doctrine\ORM\EntityRepository
{
}
