<?php

namespace AppBundle\Repository;

/**
 * MAFAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MAFAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
