<?php

namespace AppBundle\Repository;

/**
 * MAFMiscQuestionSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MAFMiscQuestionSetRepository extends \Doctrine\ORM\EntityRepository
{
}
