<?php

namespace AppBundle\Repository;

/**
 * MeShieldAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeShieldAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
