<?php

namespace AppBundle\Repository;

/**
 * MiscQuestionSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiscQuestionSetRepository extends \Doctrine\ORM\EntityRepository
{
}
