<?php

namespace AppBundle\Repository;

/**
 * MotivationWorksheetAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotivationWorksheetAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
