<?php

namespace AppBundle\Repository;

/**
 * NoteTakingAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteTakingAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
