<?php

namespace AppBundle\Repository;

/**
 * QuestionSetAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionSetAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
