<?php

namespace AppBundle\Repository;

/**
 * QuestionSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionSetRepository extends \Doctrine\ORM\EntityRepository
{
}
