<?php

namespace AppBundle\Repository;

/**
 * RegularTextareaTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegularTextareaTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
