<?php

namespace AppBundle\Repository;

/**
 * RelaxationWorksheetAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelaxationWorksheetAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
