<?php

namespace AppBundle\Repository;

/**
 * ScrolAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScrolAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
