<?php

namespace AppBundle\Repository;

/**
 * SelfAssessmentMiscQuestionSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SelfAssessmentMiscQuestionSetRepository extends \Doctrine\ORM\EntityRepository
{
}
