<?php

namespace AppBundle\Repository;

/**
 * SelfAssessmentAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SelfAssessmentAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
