<?php

namespace AppBundle\Repository;

/**
 * SessionGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
