<?php

namespace AppBundle\Repository;

/**
 * SevenWordsAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SevenWordsAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
