<?php

namespace AppBundle\Repository;

/**
 * SimplePageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SimplePageRepository extends \Doctrine\ORM\EntityRepository
{
}
