<?php

namespace AppBundle\Repository;

/**
 * TenAmpedChoiceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TenAmpedChoiceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
