<?php

namespace AppBundle\Repository;

/**
 * ThingsInCommonAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThingsInCommonAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
