<?php

namespace AppBundle\Repository;

/**
 * TICIcebreakerQuestionSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TICIcebreakerQuestionSetRepository extends \Doctrine\ORM\EntityRepository
{
}
