<?php

namespace AppBundle\Repository;

/**
 * TICTextareaTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TICTextareaTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
