<?php

namespace AppBundle\Repository;

/**
 * TimeTravelingAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeTravelingAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
