<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{    
    public function findSessionByAmpedNum($num)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb
                ->select('s')
                ->from('User', 'u')
                ->join('u.sessions', 's')
                ->join('s.ampedSession', 'a')
                ->where($qb->expr()->eq('a.num', '?1'))
                ->setParameter(1, $num)
                ->getQuery()
                ->getOneOrNullResult();
    }
}
