app:
    resource: '@AppBundle/Controller/'
    type: annotation

index_list:
    path: /
    defaults: {_controller: AppBundle:Home:index }

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin    