AppBundle\Entity\ampedsession:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ampedsessionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        num:
            type: integer
            unique: true
#        title:
#            type: string
#            length: '255'
#            nullable: true
#        description:
#            type: text
#            nullable: true  
        createdAt:
            type: datetime
        has7Words:
            type: boolean
        hasMeShield:
            type: boolean
        hasTimeTravel:
            type: boolean
        hasBackpack:
            type: boolean
        hasBackToBack:
            type: boolean
            
        hasOrgChart:
            type: boolean
        hasModules:
            type: boolean
        hasGoalSheet:
            type: boolean
    manyToOne:
        createdBy:
            targetEntity: User
        tic:
            targetEntity: TICIcebreakerQuestionSet
        abm:
            targetEntity: ABMIcebreakerQuestionSet
        changeFormQuestions:
            targetEntity: ChangeFormMiscQuestionSet
        selfAssessmentBehaviourQuestions:
            targetEntity: SelfAssessmentMiscQuestionSet
        selfAssessmentAcademicQuestions:
            targetEntity: SelfAssessmentMiscQuestionSet
        selfAssessmentSelfRegQuestions:
            targetEntity: SelfAssessmentMiscQuestionSet
        selfAssessmentSocialQuestions:
            targetEntity: SelfAssessmentMiscQuestionSet
        MAFQuestions:
            targetEntity: MAFMiscQuestionSet

    manyToMany:
        pages:
            targetEntity: SimplePage
#    manyToMany:
#        icebreakerQuestions:
#            targetEntity: IcebreakerQuestionSet
#        miscQuestions:
#            targetEntity: MiscQuestionSet  
    
    lifecycleCallbacks: {  }
