AppBundle\Entity\AmpedChoiceType:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\AmpedChoiceTypeRepository
    fields:
        groupType:
            type: integer
            nullable: false
    lifecycleCallbacks: {  }
