AppBundle\Entity\ampedsession:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ampedsessionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        num:
            type: integer
            unique: true
        title:
            type: string
            length: '255'
            nullable: true
        description:
            type: text
            nullable: true  
        createdAt:
            type: datetime
        has7Words:
            type: boolean
        hasMeShield:
            type: boolean
        hasOrgChart:
            type: boolean
        hasModules:
            type: boolean
    manyToOne:
        createdBy:
            targetEntity: User
            inversedBy: sessionsCreated
        tic:
            targetEntity: TICIcebreakerQuestionSet
        abm:
            targetEntity: ABMIcebreakerQuestionSet
        changeFormQuestions:
            targetEntity: ChangeFormMiscQuestionSet
        selfAssessmentQuestions:
            targetEntity: SelfAssessmentMiscQuestionSet
        MAFQuestions:
            targetEntity: MAFMiscQuestionSet
    oneToMany:
        sessions:
            targetEntity: Session
            mappedBy: ampedSession
#    manyToMany:
#        icebreakerQuestions:
#            targetEntity: IcebreakerQuestionSet
#        miscQuestions:
#            targetEntity: MiscQuestionSet
    
    
    
    lifecycleCallbacks: {  }
