AppBundle\Entity\Login:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\LoginRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        ts:
            type: datetime
        status:
            type: boolean
    manyToOne:
        user:
            targetEntity: User
            inversedBy: logins
    lifecycleCallbacks: {  }
