AppBundle\Entity\QuestionSet:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        set: QuestionSet
        icebreaker: IcebreakerQuestionSet
        misc: MiscQuestionSet
        self: SelfAssessmentMiscQuestionSet
        abm: ABMIcebreakerQuestionSet
        tic: TICIcebreakerQuestionSet
        change: ChangeFormMiscQuestionSet
        maf: MAFMiscQuestionSet
    table: null
    repositoryClass: AppBundle\Repository\QuestionSetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        name:
            type: string
            nullable: false
    manyToOne:
        createdBy:
            targetEntity: User
    manyToMany:
        questions:
           targetEntity: QuestionType  
           cascade: [persist, remove]
    lifecycleCallbacks: {  }