AppBundle\Entity\QuestionSetAnswers:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminator:
        name: dtype
        type: string
    discriminatorMap:
        qsanswers: QuestionSetAnswers
        mafanswers: MAFAnswers
        selfassessanswers: SelfAssessmentAnswers
        changeanswers: ChangeSurveyAnswers
        abmanswers: ABMAnswers
        ticanswers: ThingsInCommonAnswers
    table: null
    repositoryClass: AppBundle\Repository\QuestionSetAnswersRepository
    manyToOne:
        questionSet:
            targetEntity: QuestionSet
        
    lifecycleCallbacks: {  }
