AppBundle\Entity\QuestionType:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        question: QuestionType
        ampedtext: AmpedTextareaType
        ampedchoice: AmpedChoiceType
    table: null
    repositoryClass: AppBundle\Repository\QuestionTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        text:
            type: string
            nullable: true
    lifecycleCallbacks: {  }
