AppBundle\Entity\SelfAssessmentMiscQuestionSet:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SelfAssessmentMiscQuestionSetRepository
    fields:
        title:
            type: string
            nullable: true
    lifecycleCallbacks: {  }
