AppBundle\Entity\SelfAssessmentMiscQuestionSet:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SelfAssessmentMiscQuestionSetRepository
    fields:
        title:
            type: string
            nullable: true
#            joinTable:
#                name: selfquestionset_questions
#                joinColumns:
#                    selfquestionset_id:
#                        referencedColumnName: id
#                inverseJoinColumns:
#                    question_id:
#                        referencedColumnName: id
    lifecycleCallbacks: {  }
