AppBundle\Entity\Session:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SessionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        start:
            type: datetime
            nullable: true
        end:
            type: datetime
            nullable: true
        moduleCompleted:
            type: integer
            nullable: true
        icebreakerCompleted:
            type: integer
            nullable: true
    manyToOne:
        ampedSession:
            targetEntity: ampedsession
        student:
            targetEntity: User
        mentor:
            targetEntity: User
#    oneToOne:
#        icebreakerAnswers:
#            targetEntity: AnswerSet
#        moduleAnswers:
#            targetEntity: AnswerSet
    lifecycleCallbacks: {  }
