AppBundle\Entity\TenAmpedChoiceType:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        tenchoice: TenAmpedChoiceType
        adjectivechoice: AdjectiveAmpedChoiceType
        definitivechoice: DefinitiveAmpedChoiceType    
    table: null
    repositoryClass: AppBundle\Repository\TenAmpedChoiceTypeRepository
    lifecycleCallbacks: {  }
