AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: '45'
        lastName:
            type: string
            length: '45'
            nullable: true
        dob:
            type: date
        institution:
            type: string
            length: '100'
        joinDate:
            type: date
    oneToMany:
        logins:
            targetEntity: Login
            mappedBy: user
            cascade: ["remove"]
#        students:
#            targetEntity: User
#            mappedBy: mentor
#            cascade: ["remove"]
#    manyToOne:
#        mentor:
#            targetEntity: User
#            inversedBy: students
#            cascade: ["persist"]
    manyToOne:
        mentor:
            targetEntity: User

#    manyToMany:
#      sessions:
#        orderBy: {'start': 'ASC'}
#        targetEntity: Session
#        joinTable:
#          name: users_sessions
#          joinColumns:
#            user_id:
#              referencedColumnName: id
#          inverseJoinColumns:
#            session_id:
#              referencedColumnName: id                     
#      students:
#        targetEntity: User
#        joinTable:
#          name: mentors_students
#          joinColumns:
#            mentor_id:
#              referencedColumnName: id
#          inverseJoinColumns:
#            student_id:
#              referencedColumnName: id
#              unique: true           
    attributeOverride:
        emailCanonical:
            type: string
            length: 180
            unique: false
    lifecycleCallbacks: {  }
